// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjtkhqmtupesaiyrkbrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqdGtocW10dXBlc2FpeXJrYnJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MTcwNDIsImV4cCI6MjA3MDE5MzA0Mn0.e9I-BX-5D_D0XkNts-DY0a83JQrirrG3G-6B0kAxN3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});